name: run 

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */3 * *" # Means every 3 days lol

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js 23
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Install pnpm
        run: |
          npm install -g pnpm

      - name: Install dependencies
        run: |
          pnpm i

      - name: Run
        run: |
          GITHUB_TOKEN=${{ secrets.GH_TOKEN }} node .

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actor
          message: "chore: update certificate"
          add: |
           - graph.png
